### PR TITLE
BioSignal-Recorder 0.2

### PR DESCRIPTION
**Pull request by Asc91**
Reimplement frontend using Chart.js

### CODE REVIEW

**Comment by Asc91** [comment]
I'm working on improving sampling rate of esp32.

**Comment by lorforlinux** [comment]
@Asc91 can you please push your recent updates here as well?

**Comment by lorforlinux** [comment]
@Asc91 Please share images of how it looks right now and provide a detailed list of things already implemented.

**Comment by Asc91** [comment]
ADC1
ADC2

1. **Char.js Implementation:** Reimplemented previous version of BioSignal-Recorder using Chart.js , which will make future development bit easier.  
2. **Multi-channel support:** ESP32 has 4 hardware timers which are currently being used for sampling data according to provided sampling rate. User can choose number of channels to use. Graph of all channels is currently shown on same canvas maybe separate canvases should be used.
3. **Variable Sampling rate:**  Multiple options for sampling rate are given from 100Hz to 5000Hz. Every channel can be set with different sampling rate. Maybe user input should be taken for sampling rate than just providing some options.
4. **Save as CSV:** Data can be saved as a CSV file and downloaded on computer.  CSV file contains data with timestamp, channel number and packet number of corresponding channel.

**Comment by lorforlinux** [comment]
@Asc91 Thanks a lot for your contribution, everything looks great! merging it now <3

**Pull request merged**
